# Generated by Django 4.1.1 on 2022-11-13 07:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_room_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exclusion",
            name="zones",
        ),
        migrations.AddField(
            model_name="exclusion",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exclusion",
            name="hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=12),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="exclusion",
            name="role",
            field=models.CharField(
                choices=[
                    ("D", "بر اساس تاریخ"),
                    ("W", "بر اساس روز هفته"),
                    ("DW", "بر اساس روز هفته و تاریخ"),
                ],
                default="DW",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="exclusion",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exclusion",
            name="weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    blank=True,
                    choices=[
                        (1, "شنبه"),
                        (2, "یک شنبه"),
                        (3, "دو شنبه"),
                        (4, "سه شنبه"),
                        (5, "چهار شنبه"),
                        (6, "پنج شنبه"),
                        (7, "جمعه"),
                    ],
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
