version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass "itisQomRiddleHouse__2022" --save 60 1 --loglevel warning

  qom:
    build: ./qom
    # command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn riddlehouse.wsgi:application --bind 0.0.0.0:8000"
    command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./qom/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - qom_db
      - redis
  qom_db:
    image: postgres:13.0-alpine
    volumes:
      - qom_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=riddle
      - POSTGRES_PASSWORD=HEWMG!BEI@fJFc$ZA18AQ
      - POSTGRES_DB=riddlehouse
  workers_qom:
    build: ./qom
    restart: always
    command: celery -A riddlehouse worker --loglevel=info
    env_file:
      - ./.env
    depends_on:
      - redis
      - qom
    volumes:
      - ./qom/:/usr/src/app/
  # workers_ahvaz:
  #   build: ./ahvaz
  #   command: celery -A riddlehouse worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - ahvaz
  #   volumes:
  #     - ./ahvaz/:/usr/src/app/
  #   env_file:
  #     - ./.env
  # ahvaz:
  #   build: ./ahvaz
  #   command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn riddlehouse.wsgi:application --bind 0.0.0.0:9000"
  #   volumes:
  #     - ./ahvaz/:/usr/src/app/
  #   expose:
  #     - 9000
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - ahvaz_db
  # ahvaz_db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - ahvaz_postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=riddle
  #     - POSTGRES_PASSWORD=P@ssw0rdd
  #     - POSTGRES_DB=riddlehouse
  wordpress_db:
    image: mysql:5.7
    restart : always
#    ports:
#      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mehdi@1234
      MYSQL_DATABASE: riddle_wp
      MYSQL_USER: riddle
      MYSQL_PASSWORD: P@ssw0rdd
    volumes:
      - wordpress_data_volume:/var/lib/mysql
  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    restart: always
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: riddle
      WORDPRESS_DB_PASSWORD: P@ssw0rdd
      WORDPRESS_DB_NAME: riddle_wp
    volumes:
      - ./wordpress/:/var/www/html
  #certbot:
   # image: certbot/certbot
    #volumes:
     # - ./data/certbot/conf:/etc/letsencrypt
      #- ./data/certbot/www:/var/www/certbot
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    build: ./nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./qom/static/:/home/qom/static
      - ./qom/medias/:/home/qom/medias
      - ./city/:/home/select_city
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 8000:8000
      - 443:443
    depends_on:
      - qom
      - wordpress

volumes:
  qom_postgres_data:
  wordpress_data_volume:
