# Generated by Django 4.1.1 on 2022-12-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_payment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
    ]
