# Generated by Django 4.1.1 on 2022-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rest_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
