# Generated by Django 4.1.1 on 2025-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_payment_rest_payment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['room', 'reserved_time'], name='orders_orde_room_id_5cb809_idx'),
        ),
    ]
