# Generated by Django 4.1.1 on 2022-10-24 15:38

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("difficulty", models.IntegerField(blank=True, null=True)),
                ("min_players", models.IntegerField(blank=True, null=True)),
                ("max_players", models.IntegerField(blank=True, null=True)),
                (
                    "game_duration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("price_per_unit", models.IntegerField(blank=True, null=True)),
                (
                    "default_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=12),
                        size=None,
                    ),
                ),
                (
                    "default_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "شنبه"),
                                (2, "یک شنبه"),
                                (3, "دو شنبه"),
                                (4, "سه شنبه"),
                                (5, "چهار شنبه"),
                                (6, "پنج شنبه"),
                                (7, "جمعه"),
                            ]
                        ),
                        size=None,
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[("REAL", "اتاق عادی"), ("BOX", "اسکیپ باکس")],
                        default="REAL",
                        max_length=7,
                    ),
                ),
                (
                    "box_packages_prices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("warnings", models.TextField(blank=True, null=True)),
                ("banner", models.ImageField(blank=True, null=True, upload_to="rooms")),
            ],
        ),
        migrations.CreateModel(
            name="Exclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zones", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ("is_suspended", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="game.room",
                    ),
                ),
            ],
        ),
    ]
