# Generated by Django 4.1.1 on 2022-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_remove_exclusion_is_suspended_alter_exclusion_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="exclusion",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
