# Generated by Django 4.1.1 on 2022-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_room_pre_pay_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pre_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
