# Generated by Django 4.1.1 on 2022-12-10 15:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_room_pre_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='default_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
    ]
