# Generated by Django 4.1.1 on 2022-09-09 12:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("difficulty", models.IntegerField()),
                ("min_players", models.IntegerField()),
                ("max_players", models.IntegerField()),
                ("game_duration", models.CharField(max_length=255)),
                ("pre_payment", models.IntegerField()),
                ("final_payment", models.IntegerField()),
                (
                    "default_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=12),
                        size=None,
                    ),
                ),
                (
                    "default_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "شنبه"),
                                (2, "یک شنبه"),
                                (3, "دو شنبه"),
                                (4, "سه شنبه"),
                                (5, "چهار شنبه"),
                                (6, "پنج شنبه"),
                                (7, "جمعه"),
                            ]
                        ),
                        size=None,
                    ),
                ),
                (
                    "final_payment_method",
                    models.CharField(
                        choices=[("P", "Per Person"), ("T", "Total")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField()),
                ("warnings", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "rule_by",
                    models.CharField(
                        choices=[("D", "Single Day"), ("W", "Week Day")],
                        default="D",
                        max_length=1,
                    ),
                ),
                (
                    "week_day",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "شنبه"),
                            (2, "یک شنبه"),
                            (3, "دو شنبه"),
                            (4, "سه شنبه"),
                            (5, "چهار شنبه"),
                            (6, "پنج شنبه"),
                            (7, "جمعه"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="game.room",
                    ),
                ),
            ],
        ),
    ]
