# Generated by Django 4.1.1 on 2022-09-09 12:54

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ("is_suspended", models.BooleanField(default=True)),
            ],
        ),
    ]
