# Generated by Django 4.1.1 on 2022-09-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_exclusion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exclusion",
            old_name="zone",
            new_name="Apply To This Zones",
        ),
    ]
