# Generated by Django 4.1.1 on 2023-10-31 12:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusion',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='exclusion',
            name='zones',
        ),
        migrations.AddField(
            model_name='exclusion',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='role',
            field=models.CharField(choices=[('D', 'بر اساس تاریخ'), ('DW', 'بر اساس روز هفته و تاریخ')], default='DW', max_length=4),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'شنبه'), (2, 'یک شنبه'), (3, 'دو شنبه'), (4, 'سه شنبه'), (5, 'چهار شنبه'), (6, 'پنج شنبه'), (7, 'جمعه')], null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='room',
            name='admin_phones',
            field=models.CharField(blank=True, default='', max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='balad_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='google_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='pre_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='default_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='difficulty',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='VipSans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.IntegerField(blank=True, null=True)),
                ('pre_pay', models.IntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'شنبه'), (2, 'یک شنبه'), (3, 'دو شنبه'), (4, 'سه شنبه'), (5, 'چهار شنبه'), (6, 'پنج شنبه'), (7, 'جمعه')], null=True), blank=True, null=True, size=None)),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), blank=True, null=True, size=None)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vipsans', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeVipSans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('price_per_unit', models.IntegerField(blank=True, null=True)),
                ('pre_pay', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('closed', models.BooleanField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otes', to='game.room')),
            ],
        ),
    ]
