

# Generated by Django 4.1.1 on 2022-11-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_exclusion_zones_exclusion_from_date_and_more"),
    ]

    operations = [

        migrations.AlterField(
            model_name="exclusion",
            name="role",
            field=models.CharField(
                choices=[("D", "بر اساس تاریخ"), ("DW", "بر اساس روز هفته و تاریخ")],
                default="DW",
                max_length=4,
            ),
        ),
    ]
