# Generated by Django 4.1.1 on 2022-11-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_exclusion_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="difficulty",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
