# Generated by Django 4.1.1 on 2022-11-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_room_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=63),
        ),
    ]
