# Generated by Django 4.1.1 on 2022-11-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=63, null=True),
        ),
    ]
