# Generated by Django 4.1.1 on 2022-11-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=63, null=True),
        ),
    ]
