# Generated by Django 4.1.1 on 2022-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
