# Generated by Django 4.1.1 on 2022-11-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_room_modified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='balad_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='google_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
