# Generated by Django 4.1.1 on 2022-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_room_balad_link_room_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin_phones',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='room',
            name='pre_pay_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
