# Generated by Django 4.1.1 on 2022-12-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_room_default_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin_phones',
            field=models.CharField(blank=True, default='', max_length=127, null=True),
        ),
    ]
