# Generated by Django 4.1.1 on 2023-10-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_onetimeexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
