# Generated by Django 4.1.1 on 2023-10-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_vipsans_onetimevipsans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipsans',
            name='dates',
        ),
        migrations.AddField(
            model_name='vipsans',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vipsans',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
