# Generated by Django 4.1.1 on 2023-10-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_exclusion_is_suspended_remove_exclusion_zones_and_more'),
        ('game', '0018_room_is_archive_vipsans_onetimevipsans'),
        ('game', '0021_vipsans_hours'),
    ]

    operations = [
    ]
