# Generated by Django 4.1.1 on 2023-10-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_merge_20231031_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipsans',
            name='test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
