# Generated by Django 4.1.1 on 2023-10-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_vipsans_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipsans',
            name='room',
        ),
        migrations.DeleteModel(
            name='OneTimeVipSans',
        ),
        migrations.DeleteModel(
            name='VipSans',
        ),
    ]
