# Generated by Django 4.1.1 on 2023-10-31 13:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_remove_vipsans_room_delete_onetimevipsans_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipSans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.IntegerField(blank=True, null=True)),
                ('pre_pay', models.IntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'شنبه'), (2, 'یک شنبه'), (3, 'دو شنبه'), (4, 'سه شنبه'), (5, 'چهار شنبه'), (6, 'پنج شنبه'), (7, 'جمعه')], null=True), blank=True, null=True, size=None)),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), blank=True, null=True, size=None)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('test', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vipsans', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeVipSans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('price_per_unit', models.IntegerField(blank=True, null=True)),
                ('pre_pay', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
    ]
