# Generated by Django 4.1.1 on 2023-10-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_vipsans_onetimevipsans'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimevipsans',
            name='exclude',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
