# Generated by Django 4.1.1 on 2023-10-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_onetimevipsans_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimevipsans',
            name='exclude',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
