# Generated by Django 4.1.1 on 2023-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_onetimevipsans_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimevipsans',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
