# Generated by Django 4.1.1 on 2024-08-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_onetimevipsans_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
