# Generated by Django 4.1.1 on 2025-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_room_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='exclusion',
            index=models.Index(fields=['room', 'from_date', 'to_date'], name='game_exclus_room_id_67aadc_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimeexclusion',
            index=models.Index(fields=['room', 'date_time'], name='game_onetim_room_id_ba43f4_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimevipsans',
            index=models.Index(fields=['room', 'date_time', 'exclude'], name='game_onetim_room_id_aa75a6_idx'),
        ),
        migrations.AddIndex(
            model_name='vipsans',
            index=models.Index(fields=['from_date', 'to_date'], name='game_vipsan_from_da_58867d_idx'),
        ),
    ]
