# Generated by Django 4.1.1 on 2025-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_room_is_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='merchant',
            field=models.IntegerField(default=1),
        ),
    ]
