# Generated by Django 4.1.1 on 2022-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="code",
            field=models.CharField(default="", max_length=127),
            preserve_default=False,
        ),
    ]
