# Generated by Django 4.1.1 on 2022-10-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_coupon_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="used",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="rest_payment",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
